#!/usr/bin/env python
# coding: utf-8

VALUE_IMAGE_PERCENT_GAMMA_CORRECTION = 30

VALUE_IMAGE_BLACK_WHITE_DIVISION = 128

VALUE_IMAGE_BLACK_WHITE_UPDATE = 127

VALUE_IMAGE_COLORS = 255

VALUE_IMAGE_BINARY_GET = 1

MINIMUM_ARGUMENTS = 2

MINIMUM_TEXT_SIZE = 4

MINIMUM_WORD_SIZE = 2

MINIMUM_WORD_NEW_SIZE = 0

INDEX_RECOMMENDED_WORD = 0

INDEX_RETURN_OK = 0

INDEX_RETURN_ERROR = 1

INDEX_ARGUMENT_IMAGE = 1

INDEX_ARGUMENT_AUDIO = 2

INDEX_POSITION_EXTENSION = 1

INDEX_POSITION_SPLIT_ORDER = 1

COMMAND_READ_MODE = "r"

COMMAND_WRITE_MODE = "w"

COMMAND_FIX_CHARACTERS = r'[^\w\s]'

COMMAND_WRITE_FILE = u"\ufeff"

COMMAND_CREATE_FILE = "touch "

PATH_VARIABLES = "data/strings/variables.json"

PATH_LANGUAGE = "languagePath"

FIELD_EMPTY_STRING = ""

FIELD_SPACE = " "

FIELD_TEXT_TYPE = "textType"

FIELD_TEXT_TYPE_CODECS = "textTypeCodecs"

FIELD_LANGUAGE_CURRENT = "languageCurrent"

FIELD_ERROR_PARAMETERS = "errorParameters"

FIELD_ERROR_INPUT = "errorInput"

FIELD_ERROR_OUTPUT = "errorOutput"

FIELD_ERROR_FILE_TYPE = "errorFiletype"

FIELD_IMAGE_EXTENSION = "imageExtension"

FIELD_MESSAGE_WELCOME = "messageWelcome"

FIELD_MESSAGE_FINISH = "messageFinish"

FIELD_IMAGE_FILENAME = "imageFilename"

FIELD_TEXT_FILENAME = "textFilename"

FIELD_GTTS_CODE = "gTTSCode"

EXTENSION_JSON = ".json"



